spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer-service?authSource=admin
      username: admin
      password: password
      authentication-database: admin

server:
  port: 8090